# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  Shiyu-Lab/Prereq_Tune: 1.0
dataset_configs:
  - popqa_knowledge
dataset_splits:
  - passage_train_real
text_column: text
preprocessing_num_workers: 12
packing: false

# LoRA arguments
use_peft: true
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# trainer config
dataloader_num_workers: 2
bf16: true
do_train: true
do_eval: false
evaluation_strategy: "no"
save_strategy: "no"
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 3.0e-05
weight_decay: 0.1
adam_beta2: 0.95
log_level: info
logging_steps: 100
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 768
max_steps: -1
num_train_epochs: 5
overwrite_output_dir: true
per_device_train_batch_size: 8
push_to_hub: false
remove_unused_columns: true
output_dir: data
run_name: llama3_popqa_cpt_passage_real
report_to:
- wandb
seed: 42
warmup_ratio: 0.03
